// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5KiNQQr7R8xhd0_9x48w-C9-D2D2Usg',
    appId: '1:463703495790:web:6954468b79f16a2110827f',
    messagingSenderId: '463703495790',
    projectId: 'mod14asgmt-97e3e',
    authDomain: 'mod14asgmt-97e3e.firebaseapp.com',
    storageBucket: 'mod14asgmt-97e3e.appspot.com',
    measurementId: 'G-XV02STJE97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_6aZUxH0JGxtogOK6eck1N8t9MsCAfc',
    appId: '1:463703495790:android:fca5d1a19b79f7e410827f',
    messagingSenderId: '463703495790',
    projectId: 'mod14asgmt-97e3e',
    storageBucket: 'mod14asgmt-97e3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYa9_52QcLcTB8G1f8ukL3nBLKeE7Ntl8',
    appId: '1:463703495790:ios:5e7a93256fb001c510827f',
    messagingSenderId: '463703495790',
    projectId: 'mod14asgmt-97e3e',
    storageBucket: 'mod14asgmt-97e3e.appspot.com',
    iosClientId: '463703495790-8d0j52oifchmf8q2979ghvo04l2n7soc.apps.googleusercontent.com',
    iosBundleId: 'com.muj.mod14asgmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYa9_52QcLcTB8G1f8ukL3nBLKeE7Ntl8',
    appId: '1:463703495790:ios:37da6f52433447a310827f',
    messagingSenderId: '463703495790',
    projectId: 'mod14asgmt-97e3e',
    storageBucket: 'mod14asgmt-97e3e.appspot.com',
    iosClientId: '463703495790-rf85mm343255iel210ugv8vn1bujlksq.apps.googleusercontent.com',
    iosBundleId: 'com.muj.mod14asgmt.RunnerTests',
  );
}
